apiVersion: batch/v1
kind: Job
metadata:
  namespace: example02
  generateName: my-db-upgrade-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: dummy-run
          image: alpine
          command:
            - "sleep"
            - "10"
      restartPolicy: Never
  backoffLimit: 2
project: default
source:
  repoURL: "https://github.com/ishuar/gitops-cert-level-2-examples"
  path: ./sync-hooks-waves/02-presync-job
  targetRevision: cert/gitops-scale
destination:
  server: "https://kubernetes.default.svc"
  namespace: example02
syncPolicy: {}
