apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moon
  namespace: argocd
spec:
  project: aerokube
  source:
    chart: moon2
    repoURL: https://charts.aerokube.com/
    targetRevision: 2.4.0
    helm:
      values: |
          customIngress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt"   
            ingressClassName: nginx
            host: moon3.benighil-mohamed.com
            tls:
            - secretName: moon-tls
              hosts:
              - moon3.benighil-mohamed.com
          configs:
            default:
              containers:
                vnc-server:
                  repository: quay.io/aerokube/vnc-server
                  resources:
                    limits:
                      cpu: 400m
                      memory: 512Mi
                    requests:
                      cpu: 200m
                      memory: 512Mi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: moon1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      