apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: always-latest01
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: simpleapp=ghcr.io/ishuar/gitops-cert-level-2-examples
    argocd-image-updater.argoproj.io/simpleapp.update-strategy: latest
spec:
  project: default

  source:
    repoURL: https://github.com/ishuar/gitops-cert-level-2-examples.git
    targetRevision: cert/gitops-scale
    path: ./image-updater/example-app/envs/qa/

  destination:
    server: https://kubernetes.default.svc
    namespace: qa

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
